-- MySQL Script generated by MySQL Workbench
-- Mon Mar 27 09:52:39 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema infoscreen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema infoscreen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `infoscreen` DEFAULT CHARACTER SET utf8 ;
USE `infoscreen` ;

-- -----------------------------------------------------
-- Table `infoscreen`.`Sceduler`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infoscreen`.`Sceduler` ;

CREATE TABLE IF NOT EXISTS `infoscreen`.`Sceduler` (
  `idSceduler` INT NOT NULL AUTO_INCREMENT,
  `frequency` DATETIME NOT NULL,
  `duration` DATETIME NOT NULL,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NULL,
  PRIMARY KEY (`idSceduler`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infoscreen`.`Template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infoscreen`.`Template` ;

CREATE TABLE IF NOT EXISTS `infoscreen`.`Template` (
  `idTemplate` INT NOT NULL AUTO_INCREMENT,
  `HTML` VARCHAR(500) NULL,
  PRIMARY KEY (`idTemplate`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infoscreen`.`Page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infoscreen`.`Page` ;

CREATE TABLE IF NOT EXISTS `infoscreen`.`Page` (
  `idpage` INT NOT NULL AUTO_INCREMENT,
  `scedulerFK` INT NOT NULL,
  `templateFK` INT NOT NULL,
  PRIMARY KEY (`idpage`),
  INDEX `skedulerFK_idx` (`scedulerFK` ASC),
  INDEX `templateFK_idx` (`templateFK` ASC),
  CONSTRAINT `skedulerFK`
  FOREIGN KEY (`scedulerFK`)
  REFERENCES `infoscreen`.`Sceduler` (`idSceduler`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `templateFK`
  FOREIGN KEY (`templateFK`)
  REFERENCES `infoscreen`.`Template` (`idTemplate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infoscreen`.`PageContent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infoscreen`.`PageContent` ;

CREATE TABLE IF NOT EXISTS `infoscreen`.`PageContent` (
  `idPageContent` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(250) NULL,
  `img` VARCHAR(250) NULL,
  `text` VARCHAR(250) NULL,
  `pageFK` INT NOT NULL,
  PRIMARY KEY (`idPageContent`),
  INDEX `pageFK_idx` (`pageFK` ASC),
  CONSTRAINT `pageFK`
  FOREIGN KEY (`pageFK`)
  REFERENCES `infoscreen`.`Page` (`idpage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
